apiVersion: v1
kind: Pod
metadata:
  name: mlpipe-train-2
  labels:
    app: ml-app
    role: train
spec:
  nodeSelector:
    kubernetes.io/hostname: node2
  restartPolicy: OnFailure
  containers:
    - name: ml
      image: local-ml-app:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: ROLE
          value: train
        - name: LISTEN_PORT
          value: "5002"
        - name: TEST_HOST
          value: mlpipe-test
        - name: MODEL_PORT
          value: "5003"
      ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: mlpipe-train
  labels:
    app: ml-app
    role: train
spec:
  type: LoadBalancer
  ports:
    - port: 10020
      targetPort: 5002
      name: worker
    - port: 10021
      targetPort: 5002
      name: cache-server
  selector:
    app: ml-app
    role: train
  externalIPs:
    - 10.0.0.234
